server:
  port: 8082

spring:

  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          #url: jdbc:mysql://localhost:3306/mytest?serverTimezone=GMT%2B8
          url: jdbc:mysql://localhost:3306/mytest
          username: root
          password: m123456
          # 3.2.0开始支持SPI可省略此配置
          #driver-class-name: com.mysql.jdbc.Driver
#        slave_1:
#          url: jdbc:mysql://xx.xx.xx.xx:3307/dynamic
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true


  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  mapper-locations:  classpath:mybatis/mapper/*.xml
  type-aliases-package: com.gcfw.*.entity
    #configuration:
  # map-underscore-to-camel-case: true

logging:
  level:
    com:
      gcfw:
        debug


